miicTeam/miic_R_package

DESCRIPTION
src/computation_cache.h
src/compute_ens_information.cpp
src/compute_info.cpp
src/info_cnt.cpp
src/mutual_information.cpp
src/orientation_probability.cpp
src/proba_orientation.cpp
src/reconstruct.cpp
src/skeleton_iteration.cpp
src/utilities.cpp

Fixes #20, fixes #19.
For future tests see the nice package [`rhub`](https://cran.r-project.org/web/packages/rhub/)

Fix cran check

---

src/confidence_cut.cpp
src/confidence_cut.h
src/environment.cpp
src/orientation_probability.cpp
src/orientation_probability.h
src/proba_orientation.cpp
src/proba_orientation.h
src/structure.h
src/utilities.cpp
src/utilities.h

This PR introduces a major refactoring of the orientation code of MIIC, featuring
- functions restructuring;
- self-explanatory variables renaming;
- more detailed commentary.
It aims to provide a clearer logic of the orientation process without any algorithmic change except for bug fixes (c7679f2). It also facilitates future change to the orientation strategy.

Refactoring of orientation code

---

src/orientation_probability.cpp
src/proba_orientation.cpp

use fabs instead of abs for double

---

.github/workflows/network_test.yml

Ci network

---

src/compute_ens_information.cpp
src/compute_info.cpp
src/reconstruct.cpp
src/skeleton_initialization.cpp
src/skeleton_iteration.cpp

Fix #38, only removal for now, write/find a parallel logger if ever needed in the future

Remove verbose output messages in parallel blocks

---

R/miic.R
R/parseResults.R
man/miic.Rd
src/reconstruct.cpp
src/reconstruct.h
src/skeleton_iteration.cpp

A first implementation of consensus graph mainly to deal with the situation where no consistent graph can be obtained within the limited number (`max_iteration`) of iterations.

Consensus graph

---

R/miic.R
R/parseResults.R

`adj_consensus` was the consensus adjacency matrix, `summary$consensus`
contains equivalent information for consensus graph.

Replace res$adj_consensus with summary$consensus

---

src/computation_cache.cpp

Ref: https://github.com/miicTeam/miic_R_package/issues/40#issuecomment-669884707
Though it's a small improvement even without the issue.

Replace recursion with dynamic programming in logC computation

---

R/parseResults.R

Remove slow and redundant NA check, which greatly reduces execution time
and memory footprint of the function.
Fix #48.

Refactor function compute_partial_correlation()

---

R/parseResults.R

Fixes observed levels not matching provided levels

---

src/computation_continuous.cpp

Fix wrong number of levels ater resetCutPointsU.

---

src/computation_continuous.cpp

Fix wrong `lbin` value during cuts initialization.

---

src/computation_continuous.cpp
src/computation_continuous.h
src/computation_discrete.cpp
src/confidence_cut.cpp
src/environment.h
src/get_information.cpp
src/mdl_pair_discretize.cpp
src/mutual_information.cpp
src/mutual_information.h
src/skeleton.cpp
src/structure.h
src/utilities.cpp

This patch completes what has been left behind by the previous refactoring patch #63, and also has two small fixes in the continuous variables computation part. The two patches together should cover the whole C++ part of the package.
Summary:
- Better readability, simpler structure for discrete and continuous computation
- Fix #72, fix #73 
- Use faster (linear) sort during the discrete computation and the creation of data factors

Code refactoring of information computation

---

R/parseResults.R

Proper sufficient conditions for `is_causal`

---

src/skeleton.cpp

Now the function 'checkInterrupt` will be called only if enough time (kMinCheckInterval, set to 1 second) has passed since the last call. It will not be called if the whole loop finishes within the minimal interval.
Maybe related to #40.

Force time interval between user interrupt checks.

---

R/miic.R
R/parseResults.R
R/write.cytoscape.R
man/miic.Rd

A minor problem with respect to the definition of confidence: smaller value means higher confidence.

Add edge confidence colomn to edges summary, rename log_confidence to info_shifted

---

R/miic.R

Contextual flag no longer assumes variable order.

---

src/proba_orientation.cpp

1. During initialization, forced orientations will be propagated (if
possible) within all related triples, all related triples will have
their score updated (no longer restricted to triples with negative
3-point infomation). This means the orientation may now start with a
strong non-v-structure.
2. Add additional sorting rules for triples, triples with equal score
will be compared by the absolute value of their 3-point infomation.

Modify orientation rules to accommodate forced orientations

---

R/miic.R
R/miic.utils.R
R/parseResults.R

* Check required column `var_names`
* Optional columns are indeed optional now, fix #95

Proper handling of state_order file

---

src/computation_continuous.cpp
src/mdl_pair_discretize.cpp
src/structure.h

fix re-use cutpoints, see #105

---

src/environment.cpp
src/structure.h

Fix edges initialization.

---

README.md

This commit updates the README file with the latest publication related to MIIC.
It also changes a bit the formatting of where the hyperlink should be for publications
without DOI.

Add latest publication

---

src/computation_continuous.cpp

Fix issue #119: Discretization results vary depending on row order when dataset contains repeated values

Discretization takes care of duplicated values for cuts
